version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - "brandonfl"
    reviewers:
      - "brandonfl"
    allow:
      - dependency-name: "bulma"
